# 
# Do not Edit! Generated by:
# spectacle version 0.18
# 
# >> macros
# << macros

Name:       rfk
Summary:    robotfindskitten
Version:    2.0.0
Release:    1
Group:      Amusements/Games
License:    GPLv2.0
URL:        http://robotfindskitten.org
Source0:    %{name}-%{version}.tar.bz2
Source100:  rfk.yaml
Requires(post): /bin/touch
Requires(post): gtk2
BuildRequires:  pkgconfig(QtCore) >= 4.6.0
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  desktop-file-utils


%description
The story of a robot who must find a kitten



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

qmake-qt4 install_prefix=/usr
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install INSTALL_ROOT=%{buildroot}

# >> install post
# << install post
desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop



%post
/bin/touch --no-create %{_datadir}/icons/hicolor || :
%{_bindir}/gtk-update-icon-cache \
  --quiet %{_datadir}/icons/hicolor 2> /dev/null|| :

%postun
/bin/touch --no-create %{_datadir}/icons/hicolor || :
%{_bindir}/gtk-update-icon-cache \
  --quiet %{_datadir}/icons/hicolor 2> /dev/null|| :


%files
%defattr(-,root,root,-)
%{_bindir}/rfk
%{_datadir}/applications/*.desktop
%{_datadir}/icons/*.png
# >> files
# << files


